name = "social-archive"
main = "src/index.ts"
compatibility_date = "2022-11-28"
route = "social-archive.cendyne.app/*"

[site]
bucket = "./assets"

[[ d1_databases ]]
binding = "DB"
database_name = "social_archive2"
database_id = "199e8c2f-5e1c-4ea0-983a-c33dd40f2687"
preview_database_id = "199e8c2f-5e1c-4ea0-983a-c33dd40f2687"
#
