name = "social-archive"
main = "src/index.ts"
compatibility_date = "2022-11-28"
route = "social-archive.cendyne.app/*"

[site]
bucket = "./assets"

[[ d1_databases ]]
binding = "DB"
database_name = "social_archive3"
database_id = "2459777d-9762-4711-99ae-29d0560edaac"
preview_database_id = "2459777d-9762-4711-99ae-29d0560edaac"
#
